### ISSUE TITLE
Support for simple queries

### ISSUE THREAD

**Issue by mageshb** [byteally/dbrecord#11]
Support for writing simple queries. 

Following are the few that we would like to get it in
get, getBy, getAll, update
       , updateBy, updateAll, delete
       , deleteBy, deleteAll, insert
       , insertRet, upsert, count

**Comment by expipiplus1** [comment]
Doesn't `dbrecord-opaleye` do most of these?

**Comment by mageshb** [comment]
Yes. But when you want to write simple queries (which does not involve join, projections) opaleye's arrowish interface could be bit heavy weight. Thought these functions would cater to those needs as shown in the example below. 

```haskell
get :: forall db table.Table db table => (Expr sc key -> Expr sc Bool) -> Maybe table

runPG $ do
  userId10 <- get (\userId -> userId .== 10)
  return userId10
```
