### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by expipiplus1** [byteally/dbrecord#7]
It would be really nice to have some kind of TODO list for this project, or some text describing the status of `dbrecord`. It's not clear from this repo whether `dbrecord` and `dbrecord-opaleye` are ready to be used.

A TODO list would be really helpful to those wanting to contribute too!

**Comment by mageshb** [comment]
I have created milestone "Hackage release" and created tasks that we would like have completed for that.
Please feel free add any features/issues that you would like to see

**Comment by expipiplus1** [comment]
Thanks!

link here for convenience: https://github.com/byteally/dbrecord/milestone/1
